name: Azure Login

on:
  workflow_dispatch:

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps:
    - name: Log in with Azure CLI
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az webapp list --query "[].{name:name, resourceGroup:resourceGroup}" -o table 