name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend
          poetry config virtualenvs.create false
          poetry install --without dev
          pip install psycopg2-binary
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          
      - name: Collect static files
        run: |
          cd backend
          mkdir -p client/dist/static
          cp -r ../frontend/dist/* client/dist/
          DJANGO_SETTINGS_MODULE=config.settings.production python manage.py collectstatic --noinput
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
      
      # Create a deployment package with only necessary files
      - name: Create deployment package
        run: |
          mkdir -p deploy_package
          cp -r backend/* deploy_package/
          cp -r backend/.* deploy_package/ 2>/dev/null || :
          # Create a web.config file for Azure if it doesn't exist
          if [ ! -f deploy_package/web.config ]; then
            echo '<?xml version="1.0" encoding="utf-8"?>
            <configuration>
              <system.webServer>
                <handlers>
                  <add name="PythonHandler" path="*" verb="*" modules="FastCgiModule" scriptProcessor="D:\home\Python\python.exe|D:\home\Python\wfastcgi.py" resourceType="Unspecified" requireAccess="Script"/>
                </handlers>
                <rewrite>
                  <rules>
                    <rule name="Static Files" stopProcessing="true">
                      <match url="^static/.*" ignoreCase="true" />
                      <action type="Rewrite" url="^static/.*" appendQueryString="true" />
                    </rule>
                    <rule name="Configure Python" stopProcessing="true">
                      <match url="(.*)" ignoreCase="true" />
                      <action type="Rewrite" url="handler.fcgi/{R:1}" appendQueryString="true" />
                    </rule>
                  </rules>
                </rewrite>
              </system.webServer>
            </configuration>' > deploy_package/web.config
          fi
          # Create a startup script
          echo 'gunicorn --bind=0.0.0.0:8000 --workers=4 config.wsgi:application' > deploy_package/startup.sh
          chmod +x deploy_package/startup.sh
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./deploy_package
          
      - name: Run database migrations
        run: |
          cd backend
          DJANGO_SETTINGS_MODULE=config.settings.production python manage.py migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False' 