name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend
          poetry config virtualenvs.create false
          poetry install --without dev
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          
      - name: Collect static files
        run: |
          cd backend
          mkdir -p client/dist/static
          cp -r ../frontend/dist/* client/dist/
          DJANGO_SETTINGS_MODULE=config.settings.production python manage.py collectstatic --noinput
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
      
      - name: Log in to Azure
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: .
          
      - name: Run database migrations
        run: |
          cd backend
          DJANGO_SETTINGS_MODULE=config.settings.production python manage.py migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False' 