name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend
          poetry config virtualenvs.create false
          poetry install --without dev
          pip install psycopg2-binary gunicorn whitenoise
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          
      - name: Prepare deployment package
        run: |
          # Create proper directory structure for Azure
          mkdir -p backend/client/dist/static
          cp -r frontend/dist/* backend/client/dist/
          
          # Ensure web.config is in the root directory
          cp web.config backend/
          cp startup.sh backend/
          chmod +x backend/startup.sh
          
          # Collect static files
          cd backend
          DJANGO_SETTINGS_MODULE=config.settings.azure python manage.py collectstatic --noinput
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
          WEBSITE_HOSTNAME: ${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net
      
      - name: Create deployment ZIP
        run: |
          cd backend
          zip -r ../deployment.zip .

      - name: Debug ZIP File  # Debugging step
        run: |
          ls -lah deployment.zip
          unzip -l deployment.zip  # List contents of the TAR file
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./deployment.zip
          
      - name: Run database migrations
        run: |
          cd backend
          DJANGO_SETTINGS_MODULE=config.settings.azure python manage.py migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
          WEBSITE_HOSTNAME: ${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net
